DELETE FROM VENDAS.CLIENTES;
INSERT INTO VENDAS.CLIENTES (CODIGO, NOME, LIMITE) VALUES ('C0001', 'Cliente Um', 1500.50);
INSERT INTO VENDAS.CLIENTES (CODIGO, NOME, LIMITE) VALUES ('C0002', 'Cliente Dois', 900.00);
